#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts /tmp
mount -t devpts devpts /dev/pts
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tracefs none /sys/kernel/tracing
mount -t tmpfs tmpfs /tmp
if [ -b /dev/sda ]; then
    mount /dev/sda /root
fi
hostname -F /etc/hostname

# Setup network

ip link set up dev eth0
ip addr add 10.0.2.15/24 dev eth0
ip r add 0.0.0.0/0 via 10.0.2.2 dev eth0

dropbear -BRP /tmp/dropbear.pid
ret=$?
if [ $ret -ne 0 ]; then
    echo "Failed to launch dropbear, exit code $ret"
fi

echo "Minimal linux with busybox"
export ENV="$HOME/.ashrc"
while :
do
    # exec /bin/sh
    # setsid cttyhack /bin/sh
    getty 0 ttyS0
done
